export const DummyPostInformation = [
   {
      id: "1",
      userId: "1",
      username: "LeafyExcitement",
      picture: "../../sampleImages/post_tree.png",
      caption:
         "A symbol of resilience and growth, this majestic tree stands as a testament to nature’s ability to thrive through time. With roots deep in the earth and branches stretching toward the heavens, it tells a story of patience, endurance, and the quiet beauty of the natural world. Every leaf whispers the secrets of the forest, every twist in the trunk a chapter in a centuries-old tale. 🌳✨",
      dateCreated: "08/20/2025",
      timeCreated: "5 Minutes",
      location: { lat: 40.770410225094494, lng: -73.97249491935321 },
      likes: 5,
      postLikeState: false,
      comments: [
         {
            id: "1",
            text: "This tree is so beautiful, I love its vibrant green leaves!",
            username: "treeLover123",
            date: "09/01/2025",
            likes: 14,
            likeStatus: true,
         },
         {
            id: "2",
            text: "I love how the oak tree's branches stretch out. It's majestic!",
            username: "natureFan",
            date: "09/02/2025",
            likes: 22,
            likeStatus: false,
         },
         {
            id: "3",
            text: "It's amazing how trees provide oxygen and shade. They are life!",
            username: "ecoWarrior",
            date: "09/03/2025",
            likes: 30,
            likeStatus: true,
         },
         {
            id: "4",
            text: "Have you ever seen a giant sequoia? It's mind-blowing how tall they grow!",
            username: "treeHugger55",
            date: "09/04/2025",
            likes: 18,
            likeStatus: false,
         },
         {
            id: "5",
            text: "Planting trees is such a simple way to help the environment.",
            username: "greenThumb",
            date: "09/05/2025",
            likes: 12,
            likeStatus: true,
         },
         {
            id: "6",
            text: "The way trees change color in the fall is always so magical.",
            username: "autumnLover",
            date: "09/06/2025",
            likes: 27,
            likeStatus: false,
         },
         {
            id: "7",
            text: "I think I read that some trees can live for over a thousand years. Incredible!",
            username: "forestExplorer",
            date: "09/07/2025",
            likes: 9,
            likeStatus: true,
         },
         {
            id: "8",
            text: "I planted a sapling in my backyard today. Can’t wait to see it grow into a mighty oak!",
            username: "futureForest",
            date: "09/08/2025",
            likes: 35,
            likeStatus: false,
         },
         {
            id: "9",
            text: "The roots of trees are so important for preventing soil erosion. They protect the earth!",
            username: "earthDefender",
            date: "09/09/2025",
            likes: 21,
            likeStatus: true,
         },
         {
            id: "10",
            text: "I once visited the Amazon rainforest. The trees there are like nothing else on earth.",
            username: "wildLifeAdventurer",
            date: "09/10/2025",
            likes: 45,
            likeStatus: false,
         },
      ],
   },

   {
      id: "2",
      userId: "2",
      username: "StreetEatsNYC",
      picture: "../../sampleImages/hot_dog_cart.png",
      caption:
         "Sizzling sausages, the hum of the city, and the unmistakable aroma of grilled onions – nothing says NYC like a classic hotdog stand on a bustling Manhattan corner. This little cart has been serving hungry New Yorkers and tourists alike for decades, offering a quick bite with big flavor. From Wall Street suits to wide-eyed visitors, everyone finds common ground in a good hotdog. 🌭🗽🔥",
      dateCreated: "09/30/2025",
      timeCreated: "15 Minutes",
      location: { lat: 40.7906010583278, lng: -73.96654679227434 },
      likes: 5,
      postLikeState: false,
      comments: [
         {
            id: "1",
            text: "This cart is legendary! I used to grab a hotdog here every day after work.",
            username: "nycFoodie89",
            date: "10/01/2025",
            likes: 31,
            likeStatus: true,
         },
         {
            id: "2",
            text: "The smell of grilled onions in the air always draws me in. Pure NYC magic.",
            username: "urbanEater",
            date: "10/02/2025",
            likes: 24,
            likeStatus: false,
         },
         {
            id: "3",
            text: "Can we talk about how crispy the buns are? Game changer.",
            username: "hotdogLover777",
            date: "10/03/2025",
            likes: 18,
            likeStatus: true,
         },
         {
            id: "4",
            text: "Visited New York last month and this cart was a highlight. So good!",
            username: "travelBug5",
            date: "10/04/2025",
            likes: 39,
            likeStatus: false,
         },
         {
            id: "5",
            text: "Nothing beats grabbing a hotdog while watching the taxis zoom by.",
            username: "cityWalker",
            date: "10/05/2025",
            likes: 22,
            likeStatus: true,
         },
         {
            id: "6",
            text: "I swear the secret is in the mustard. It has a kick I’ve never had anywhere else.",
            username: "mustardMaestro",
            date: "10/06/2025",
            likes: 15,
            likeStatus: false,
         },
         {
            id: "7",
            text: "Street food like this is the soul of New York. Forget fancy restaurants!",
            username: "biteSizedBigApple",
            date: "10/07/2025",
            likes: 27,
            likeStatus: true,
         },
         {
            id: "8",
            text: "Met the vendor once – nicest guy ever. Even gave my kid an extra dog for free.",
            username: "dadOnTheGo",
            date: "10/08/2025",
            likes: 33,
            likeStatus: false,
         },
         {
            id: "9",
            text: "Do they take Venmo now? Asking for a very hungry friend.",
            username: "digitalNomNoms",
            date: "10/09/2025",
            likes: 11,
            likeStatus: true,
         },
         {
            id: "10",
            text: "This hotdog stand is a must-stop every time I visit NYC. Pure nostalgia in a bun.",
            username: "memoryMuncher",
            date: "10/10/2025",
            likes: 42,
            likeStatus: false,
         },
      ],
   },

   {
      id: "3",
      userId: "3",
      username: "HoopsInTheCity",
      picture: "../../sampleImages/basketball.png",
      caption:
         "Cracked pavement, chain nets, and the sound of sneakers squeaking on concrete — this is where legends are born. NYC street courts are more than just places to play; they're battlegrounds, community hubs, and open-air arenas filled with raw talent and heart. Whether you're watching a pickup game in Harlem or catching the sunset over a Lower East Side court, there's nothing quite like New York City basketball. 🏀🗽🔥",
      dateCreated: "09/28/2025",
      timeCreated: "30 Minutes",
      location: { lat: 40.78125927637364, lng: -73.9870978779928 },
      likes: 5,
      postLikeState: false,
      comments: [
         {
            id: "1",
            text: "This court brings back memories! I used to play here every summer growing up.",
            username: "BKballer91",
            date: "09/29/2025",
            likes: 36,
            likeStatus: true,
         },
         {
            id: "2",
            text: "That chain net swish sound hits different. Pure streetball vibes.",
            username: "netSnapper",
            date: "09/30/2025",
            likes: 28,
            likeStatus: false,
         },
         {
            id: "3",
            text: "If you haven’t hooped in NYC, have you even hooped at all?",
            username: "courtKing23",
            date: "09/30/2025",
            likes: 22,
            likeStatus: true,
         },
         {
            id: "4",
            text: "Caught a game here last week — the intensity was wild. Real passion.",
            username: "gameWatcher",
            date: "09/30/2025",
            likes: 19,
            likeStatus: false,
         },
         {
            id: "5",
            text: "It’s the energy for me. Every court has its own soul in this city.",
            username: "cityPulse",
            date: "10/01/2025",
            likes: 25,
            likeStatus: true,
         },
         {
            id: "6",
            text: "One-on-one after school, no refs, just pride and grit.",
            username: "streetLegend",
            date: "10/01/2025",
            likes: 14,
            likeStatus: false,
         },
         {
            id: "7",
            text: "You never know who you’ll run into at these courts. Could be future NBA.",
            username: "talentScoutNY",
            date: "10/02/2025",
            likes: 31,
            likeStatus: true,
         },
         {
            id: "8",
            text: "Played pickup here last summer. Got dunked on and earned respect. 😂",
            username: "ballDontLie",
            date: "10/02/2025",
            likes: 44,
            likeStatus: false,
         },
         {
            id: "9",
            text: "Street hoops are raw and real. No fancy gym, just love for the game.",
            username: "trueToTheGame",
            date: "10/03/2025",
            likes: 20,
            likeStatus: true,
         },
         {
            id: "10",
            text: "The golden hour lighting on that court is 🔥. So cinematic.",
            username: "lensOnTheStreets",
            date: "10/03/2025",
            likes: 27,
            likeStatus: false,
         },
      ],
   },

   {
      id: "4",
      userId: "4",
      username: "KnicksFaithful",
      picture: "../../sampleImages/madison_square.png",
      caption:
         "Madison Square Garden — where the Knicks reminded us what heart and hustle look like. Last season wasn’t just progress, it was pride. 🗽🏀🔥",
      dateCreated: "10/01/2025",
      timeCreated: "45 Minutes",
      location: { lat: 40.75070759053774, lng: -73.99351382221722 },
      likes: 5,
      postLikeState: false,
      comments: [
         {
            id: "1",
            text: "MSG was electric all season. You could *feel* the energy through the screen.",
            username: "blueAndOrangeSoul",
            date: "10/02/2025",
            likes: 29,
            likeStatus: true,
         },
         {
            id: "2",
            text: "Jalen Brunson really proved he’s *that* guy. What a leader.",
            username: "nycBuckets",
            date: "10/02/2025",
            likes: 34,
            likeStatus: false,
         },
         {
            id: "3",
            text: "Haven’t felt this proud to be a Knicks fan in years. The culture shift is real.",
            username: "loyalSince98",
            date: "10/03/2025",
            likes: 22,
            likeStatus: true,
         },
         {
            id: "4",
            text: "Playoff atmosphere at the Garden hits different. No other arena like it.",
            username: "msgSeasonTix",
            date: "10/03/2025",
            likes: 18,
            likeStatus: false,
         },
         {
            id: "5",
            text: "Still thinking about that OT win against Boston. What a game!",
            username: "clutchTalks",
            date: "10/04/2025",
            likes: 25,
            likeStatus: true,
         },
      ],
   },

   {
      id: "5",
      userId: "5",
      username: "CityEatsReview",
      picture: "../../sampleImages/italian.png",
      caption:
         "Stopped by one of NYC’s most talked-about Italian spots last night. Great ambiance, decent food — maybe not quite the hype, but still a solid night out. 🍝🗽",
      dateCreated: "10/03/2025",
      timeCreated: "1 Hour",
      location: { lat: 40.80422532655009, lng: -73.96364419806446 },
      likes: 5,
      postLikeState: false,
      comments: [
         {
            id: "1",
            text: "Totally agree. The pasta was good, but the service felt a bit rushed.",
            username: "honestFork",
            date: "10/03/2025",
            likes: 17,
            likeStatus: true,
         },
         {
            id: "2",
            text: "I went last month! Vibes were amazing, but the carbonara was just okay.",
            username: "foodieOnPrince",
            date: "10/03/2025",
            likes: 21,
            likeStatus: false,
         },
         {
            id: "3",
            text: "It’s one of those places you go for the name, not necessarily the flavor.",
            username: "platePerspective",
            date: "10/04/2025",
            likes: 13,
            likeStatus: true,
         },
         {
            id: "4",
            text: "Honestly expected more for the price. Not bad, just not memorable.",
            username: "cityTastebuds",
            date: "10/04/2025",
            likes: 19,
            likeStatus: false,
         },
         {
            id: "5",
            text: "I liked the tiramisu, but yeah — not sure I'd wait in line again.",
            username: "dessertFirstAlways",
            date: "10/05/2025",
            likes: 25,
            likeStatus: true,
         },
      ],
   },

   {
      id: "6",
      userId: "6",
      username: "CityEatsReview",
      picture: "../../sampleImages/italian.png",
      caption:
         "Finally tried the Italian spot everyone's been talking about — and honestly, it lived up to the hype. Rich flavors, warm atmosphere, and top-tier service. Not sure what the complaints are about. 🍷🍝🔥",
      dateCreated: "10/04/2025",
      timeCreated: "35 Minutes",
      location: { lat: 40.804343405866945, lng: -73.96373779466532 },
      likes: 5,
      postLikeState: false,
      comments: [
         {
            id: "25",
            text: "This thread is more dramatic than the tiramisu reveal.",
            username: "lurkingLinguini",
            date: "05/23/2025",
            likes: 14,
            likeStatus: false,
         },
         {
            id: "5",
            text: "Went in skeptical, walked out planning my next reservation. That’s how good it was.",
            username: "forkYeahNYC",
            date: "05/19/2025",
            likes: 31,
            likeStatus: false,
         },
         {
            id: "24",
            text: "I think y’all are confusing atmosphere with quality.",
            username: "ambienceIsntTaste",
            date: "05/16/2025",
            likes: 19,
            likeStatus: true,
         },
         {
            id: "4",
            text: "Sat at the chef’s counter — incredible experience. You could taste the effort.",
            username: "openKitchenFan",
            date: "05/12/2025",
            likes: 15,
            likeStatus: false,
         },
         {
            id: "23",
            text: "Okay but the panna cotta? PERFECTION.",
            username: "dessertedMe",
            date: "05/09/2025",
            likes: 23,
            likeStatus: false,
         },
         {
            id: "3",
            text: "People just love to complain. This place nailed it from apps to dessert.",
            username: "noComplaintsClub",
            date: "05/05/2025",
            likes: 24,
            likeStatus: false,
         },
         {
            id: "22",
            text: "Went twice. First time amazing, second time… meh. Inconsistent.",
            username: "roundTwoReview",
            date: "05/01/2025",
            likes: 17,
            likeStatus: true,
         },
         {
            id: "21",
            text: "It’s not gatekeeping to call bad food bad. Period.",
            username: "spicyOpinion",
            date: "04/28/2025",
            likes: 13,
            likeStatus: true,
         },
         {
            id: "2",
            text: "I had the same experience — cozy, classy, and the wine pairing was on point.",
            username: "vinoVeritas",
            date: "04/24/2025",
            likes: 19,
            likeStatus: false,
         },
         {
            id: "20",
            text: "We all have different palates. Let's not gatekeep taste buds.",
            username: "flavorMediator",
            date: "04/21/2025",
            likes: 8,
            likeStatus: false,
         },
         {
            id: "19",
            text: "Fair point. But mine *was* hot and timely. Maybe just unlucky?",
            username: "diplomaticDish",
            date: "04/17/2025",
            likes: 9,
            likeStatus: false,
         },
         {
            id: "1",
            text: "Thank you! I thought the same thing. That truffle ravioli was next-level.",
            username: "pastaislife",
            date: "04/13/2025",
            likes: 28,
            likeStatus: false,
         },
         {
            id: "18",
            text: "We get it, you're a foodie. Some of us want food that's hot and timely.",
            username: "realityEater",
            date: "04/10/2025",
            likes: 15,
            likeStatus: true,
         },
         {
            id: "17",
            text: "Mid? I nearly cried eating that carbonara. Unreal.",
            username: "pastadrenaline",
            date: "04/06/2025",
            likes: 20,
            likeStatus: false,
         },
         {
            id: "16",
            text: "Honestly, it was mid. Nothing terrible, just not worth the hype.",
            username: "balancedBite",
            date: "04/02/2025",
            likes: 12,
            likeStatus: true,
         },
         {
            id: "15",
            text: "Have you even had real Italian food? Because this was close.",
            username: "romeOnMyMind",
            date: "03/29/2025",
            likes: 10,
            likeStatus: false,
         },
         {
            id: "14",
            text: "Can’t believe people are defending this place. Absolute letdown.",
            username: "expectBetter",
            date: "03/25/2025",
            likes: 14,
            likeStatus: true,
         },
         {
            id: "13",
            text: "The truffle aroma hit before the plate even landed. Amazing.",
            username: "bitesAndBougie",
            date: "03/21/2025",
            likes: 18,
            likeStatus: false,
         },
         {
            id: "12",
            text: "LOL people expecting Olive Garden prices at a fine dining spot.",
            username: "snobbySauce",
            date: "03/17/2025",
            likes: 16,
            likeStatus: false,
         },
         {
            id: "11",
            text: "Tasted like something from a frozen dinner box. Not impressed.",
            username: "microwaveGourmet",
            date: "03/14/2025",
            likes: 22,
            likeStatus: true,
         },
         {
            id: "10",
            text: "You waited because it's popular. Good food takes time.",
            username: "defNotAChef",
            date: "03/10/2025",
            likes: 13,
            likeStatus: false,
         },
         {
            id: "9",
            text: "Service was a disaster. Took 40 minutes for our appetizer.",
            username: "waited4ever",
            date: "03/06/2025",
            likes: 9,
            likeStatus: true,
         },
         {
            id: "8",
            text: "I thought it was charming and authentic. Some people just want to complain.",
            username: "italianSoul",
            date: "03/02/2025",
            likes: 21,
            likeStatus: false,
         },
         {
            id: "7",
            text: "If you call bland pasta and soggy breadsticks 'next-level,' sure.",
            username: "chefBoyarNo",
            date: "03/01/2025",
            likes: 17,
            likeStatus: true,
         },
         {
            id: "6",
            text: "Overpriced and overhyped. You’re paying for the name, not the food.",
            username: "realTalkRita",
            date: "03/01/2025",
            likes: 11,
            likeStatus: true,
         },
      ],
   },
];
